language: node_js
node_js:
  - 6.3.1
branches:
  only: 4.x
before_install: null
before_script: null
script:
  - echo "nothing"
after_script:
  - set -e
  - mkdir gh-pages
  - mv dist demo nar bower.json ./gh-pages
  - cd gh-pages
  - git init
  - git checkout -b gh-pages
  - npm install -g bower
  - bower install
  - git status
  - git add -f dist demo nar bower_components
  - git commit -am "travis-auto-update"
  - git status
  - git ls-files
  - >-
    [ "$TRAVIS_BRANCH" == "4.x" ] && [ $GH_TOKEN ] && git push --force --quiet
    "https://${GH_TOKEN}@github.com/Ikagaka/Balloon.js.git" gh-pages:gh-pages >
    /dev/null 2>&1
  - cd ..
  - 'git clone https://github.com/Ikagaka/cuttlebone.git'
  - cd cuttlebone
  - git checkout dev
  - ls -la
  - npm run setup
  - npm run init
  - git status
  - git commit -am "travis-auto-update"
  - git status
  - git ls-files
  - >-
    [ "$TRAVIS_BRANCH" == "5.x" ] && [ $GH_TOKEN ] && git push --quiet
    "https://${GH_TOKEN}@github.com/Ikagaka/cuttlebone.git" dev:dev > /dev/null
    2>&1
env:
  global:
    - GIT_COMMITTER_NAME=legokichi
    - GIT_COMMITTER_EMAIL=legokichi@gmail.com
    - GIT_AUTHOR_NAME=legokichi
    - GIT_AUTHOR_EMAIL=legokichi@gmail.com
    - secure: >-
        LD6fCU5kyu7MhgUaYrDHEwD0TvL4/lMluIrIgAGGhGo/MkueZe4zFVA4JI+wEQU9k/Ig6g72qX5s21QPvMqSs/wzzaRcgzaRg1k7n9bfEIkEntMyanH47IFuvTpswu4HtdLeiogqy44y12xb2W9uJwry8ggXEd2AWVxj2BqwUZ4=
